trigger: 
  branches:
    include:
      - master

jobs:
  - job: Checks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - script: |
        yarn
        yarn build
      displayName: 'Install and build packages'
  - job: deployment
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
    - script: echo "To implement"
  

# resources:
#   pipelines:
#   - pipeline: theopenmarket.tom-web
#     trigger: 
#       branches:
#       - releases/*
#       - master
#     jobs:
#     
# repositories:
# - repository: myPHPApp      
#   type: GitHub
#   connection: myGitHubConnection
#   source: ashokirla/phpApp
#   pr: 
#     branches:
#     - master
#     - releases/*
