parameters:
  - name: doThing
    default: false # value passed to the condition
    type: boolean

  # stages:
    # - name: stageeee
    jobs:
    - script: echo I did a thing
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - job: B
      steps:

# resources:
#   pipelines:
#   - pipeline: theopenmarket.tom-web
#     trigger: 
#       branches:
#       - releases/*
#       - master
#     jobs:
#     - job: Checks
#     pool:
#     vmImage: 'ubuntu-latest'
#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '14.x'
#       displayName: 'Install Node.js'

#     - script: |
#       yarn
#       yarn build
#     displayName: 'Install and build packages'
# repositories:
# - repository: myPHPApp      
#   type: GitHub
#   connection: myGitHubConnection
#   source: ashokirla/phpApp
#   pr: 
#     branches:
#     - master
#     - releases/*
