jobs:

- job: Checks
  trigger:
  - master

  pr:
  - master
  - releases/*

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
      yarn build
    displayName: 'Install and build packages'
