app:
  env: 'development'
  seo:
    title: 'The Open Market'
    description: 'Buy directly with real commerces, sell directly to your customers'
  router:
    authentication:
      signIn: '/signin'
      signUp: '/signup'
    search: '/search'
  api:
    routes:
      state: '/'
      authentication:
        signIn: '/auth/signin'
        signUp: '/auth/signup'
      me:
        get: '/me'