app:
  pageTitle: 'The Open Market'
  router:
    authentication:
      signIn: '/signin'
      signUp: '/signup'
    search: '/search'
  api:
    routes:
      state: '/'
      authentication:
        signIn: '/auth/signin'
        signUp: '/auth/signup'
      me:
        get: '/me'