name: Continuous integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
            echo "::set-env name=VERCEL_ARGS::"
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=VERCEL_ARGS::--prod"
      - name: Deploy to vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
#           github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: ${{ env.VERCEL_ARGS }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
#           working-directory: ./sub-directory #Your Working Directory, Optional
#           alias-domains: | #Optional
#             staging.angular.vercel-action.amond.dev
#             pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
